### PR TITLE
User CRUD

### PR DESCRIPTION
**Pull request by rhtakaha**
Added basically full CRUD capabilities for the User collection.

Testing is almost 100% except for testing for when a "find all users" fails which I think only makes sense if there are no users to find. I can add the local memory db connection as mentioned in class and test this failure state at the beginning when nothing is there.

Everything else should be fine

### CODE REVIEW

**Comment by camilleparadis** [comment]
It looks good to me! Good work Ryan!!

**Review by camilleparadis — APPROVED** [review]
Looks good to me! Good work Ryan!!

**Review by sujanyasrinath — APPROVED** [review]
Looks good to me Ryan!

**Review by jkailee — APPROVED** [review]
LGTM you have a lot of commented blocks that could be removed but that just makes it prettier

**Pull request merged**
