### PR TITLE
Login pages

### PR DESCRIPTION
**Pull request by camilleparadis**
Added user interface, connected front end to database. Change in Launch, Login, Register.

### CODE REVIEW

**Review by rhtakaha — CHANGES_REQUESTED** [review]
I believe the Login page still has the unsupported/unrecognized font so that should be changed/removed.
Other than that, LGTM

**Comment by sujanyasrinath** [comment]
It looks good to me Camille!

**Review by sujanyasrinath — APPROVED** [review]
It looks good to me Camille!

**Review by jkailee — CHANGES_REQUESTED** [review]
Change the hardcoded IP address to the azure website https://what2keep.azurewebsites.net/

Also echoing what ryan said, either we need to include the fonts missing or not use them

**Review by rhtakaha — APPROVED** [review]

**Review by jkailee — APPROVED** [review]
Looks Good!

**Pull request merged**
